version: '3.5'
services:

  db:
    image: quay.io/ahappypie/mariadb:10.3-myrocks
    container_name: myrocks-marschat
    ports:
    - "3306:3306"
    volumes:
    - ./data/mysql:/var/lib/mysql
    networks:
      - marschat-dev-net
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r3dpl4n3t
      MYSQL_DATABASE: marschat

  redis-delay:
    image: redis:alpine
    container_name: redis-delay-marschat
    command: redis-server --appendonly yes
    ports:
    - "6379:6379"
    volumes:
    - ./data/redis/delay:/data
    networks:
      - marschat-dev-net

networks:
  marschat-dev-net:
    name: marschat-dev-net
    driver: bridge